services:
  db:
    image: postgres:17
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 21300:5432
    volumes:
      - ./sql:/sql
      - ./sql/001_schema.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - 21301:8080
