-- name: GetPlaylists :many
SELECT
  -- artwork
  p.description,
  -- permalink
  -- id
  p.is_album,
  p.is_delete,
  p.is_image_autogenerated,
  p.is_private,
  p.is_scheduled_release,
  p.is_stream_gated,
  -- is_streamable,

  p.playlist_name,

  p.playlist_id,
  p.playlist_owner_id,
  p.playlist_contents,

  p.blocknumber,

  repost_count,
  save_count as favorite_count,
  created_at,
  updated_at,
  release_date,

  (
    SELECT count(*) > 0
    FROM reposts
    WHERE @my_id > 0
      AND user_id = @my_id
      AND repost_type != 'track'
      AND repost_item_id = p.playlist_id
      AND is_delete = false
  ) AS has_current_user_reposted,

  (
    SELECT count(*) > 0
    FROM saves
    WHERE @my_id > 0
      AND user_id = @my_id
      AND save_type != 'track'
      AND save_item_id = p.playlist_id
      AND is_delete = false
  ) AS has_current_user_saved

FROM playlists p
JOIN aggregate_playlist using (playlist_id)
WHERE is_delete = false
  and playlist_id = ANY(@ids::int[])
;
