// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: fumarole.proto

package fumarole

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fumarole_GetConsumerGroupInfo_FullMethodName = "/fumarole.Fumarole/GetConsumerGroupInfo"
	Fumarole_ListConsumerGroups_FullMethodName   = "/fumarole.Fumarole/ListConsumerGroups"
	Fumarole_DeleteConsumerGroup_FullMethodName  = "/fumarole.Fumarole/DeleteConsumerGroup"
	Fumarole_CreateConsumerGroup_FullMethodName  = "/fumarole.Fumarole/CreateConsumerGroup"
	Fumarole_DownloadBlock_FullMethodName        = "/fumarole.Fumarole/DownloadBlock"
	Fumarole_SubscribeData_FullMethodName        = "/fumarole.Fumarole/SubscribeData"
	Fumarole_GetChainTip_FullMethodName          = "/fumarole.Fumarole/GetChainTip"
	Fumarole_Subscribe_FullMethodName            = "/fumarole.Fumarole/Subscribe"
	Fumarole_Version_FullMethodName              = "/fumarole.Fumarole/Version"
	Fumarole_GetSlotRange_FullMethodName         = "/fumarole.Fumarole/GetSlotRange"
)

// FumaroleClient is the client API for Fumarole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FumaroleClient interface {
	GetConsumerGroupInfo(ctx context.Context, in *GetConsumerGroupInfoRequest, opts ...grpc.CallOption) (*ConsumerGroupInfo, error)
	ListConsumerGroups(ctx context.Context, in *ListConsumerGroupsRequest, opts ...grpc.CallOption) (*ListConsumerGroupsResponse, error)
	DeleteConsumerGroup(ctx context.Context, in *DeleteConsumerGroupRequest, opts ...grpc.CallOption) (*DeleteConsumerGroupResponse, error)
	CreateConsumerGroup(ctx context.Context, in *CreateConsumerGroupRequest, opts ...grpc.CallOption) (*CreateConsumerGroupResponse, error)
	DownloadBlock(ctx context.Context, in *DownloadBlockShard, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataResponse], error)
	// Represents subscription to the data plane
	SubscribeData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataCommand, DataResponse], error)
	GetChainTip(ctx context.Context, in *GetChainTipRequest, opts ...grpc.CallOption) (*GetChainTipResponse, error)
	// Represents subscription to the control plane
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlCommand, ControlResponse], error)
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
	GetSlotRange(ctx context.Context, in *GetSlotRangeRequest, opts ...grpc.CallOption) (*GetSlotRangeResponse, error)
}

type fumaroleClient struct {
	cc grpc.ClientConnInterface
}

func NewFumaroleClient(cc grpc.ClientConnInterface) FumaroleClient {
	return &fumaroleClient{cc}
}

func (c *fumaroleClient) GetConsumerGroupInfo(ctx context.Context, in *GetConsumerGroupInfoRequest, opts ...grpc.CallOption) (*ConsumerGroupInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumerGroupInfo)
	err := c.cc.Invoke(ctx, Fumarole_GetConsumerGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) ListConsumerGroups(ctx context.Context, in *ListConsumerGroupsRequest, opts ...grpc.CallOption) (*ListConsumerGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumerGroupsResponse)
	err := c.cc.Invoke(ctx, Fumarole_ListConsumerGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) DeleteConsumerGroup(ctx context.Context, in *DeleteConsumerGroupRequest, opts ...grpc.CallOption) (*DeleteConsumerGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConsumerGroupResponse)
	err := c.cc.Invoke(ctx, Fumarole_DeleteConsumerGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) CreateConsumerGroup(ctx context.Context, in *CreateConsumerGroupRequest, opts ...grpc.CallOption) (*CreateConsumerGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConsumerGroupResponse)
	err := c.cc.Invoke(ctx, Fumarole_CreateConsumerGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) DownloadBlock(ctx context.Context, in *DownloadBlockShard, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fumarole_ServiceDesc.Streams[0], Fumarole_DownloadBlock_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadBlockShard, DataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_DownloadBlockClient = grpc.ServerStreamingClient[DataResponse]

func (c *fumaroleClient) SubscribeData(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataCommand, DataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fumarole_ServiceDesc.Streams[1], Fumarole_SubscribeData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataCommand, DataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_SubscribeDataClient = grpc.BidiStreamingClient[DataCommand, DataResponse]

func (c *fumaroleClient) GetChainTip(ctx context.Context, in *GetChainTipRequest, opts ...grpc.CallOption) (*GetChainTipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChainTipResponse)
	err := c.cc.Invoke(ctx, Fumarole_GetChainTip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlCommand, ControlResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fumarole_ServiceDesc.Streams[2], Fumarole_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlCommand, ControlResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_SubscribeClient = grpc.BidiStreamingClient[ControlCommand, ControlResponse]

func (c *fumaroleClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, Fumarole_Version_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fumaroleClient) GetSlotRange(ctx context.Context, in *GetSlotRangeRequest, opts ...grpc.CallOption) (*GetSlotRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSlotRangeResponse)
	err := c.cc.Invoke(ctx, Fumarole_GetSlotRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FumaroleServer is the server API for Fumarole service.
// All implementations must embed UnimplementedFumaroleServer
// for forward compatibility.
type FumaroleServer interface {
	GetConsumerGroupInfo(context.Context, *GetConsumerGroupInfoRequest) (*ConsumerGroupInfo, error)
	ListConsumerGroups(context.Context, *ListConsumerGroupsRequest) (*ListConsumerGroupsResponse, error)
	DeleteConsumerGroup(context.Context, *DeleteConsumerGroupRequest) (*DeleteConsumerGroupResponse, error)
	CreateConsumerGroup(context.Context, *CreateConsumerGroupRequest) (*CreateConsumerGroupResponse, error)
	DownloadBlock(*DownloadBlockShard, grpc.ServerStreamingServer[DataResponse]) error
	// Represents subscription to the data plane
	SubscribeData(grpc.BidiStreamingServer[DataCommand, DataResponse]) error
	GetChainTip(context.Context, *GetChainTipRequest) (*GetChainTipResponse, error)
	// Represents subscription to the control plane
	Subscribe(grpc.BidiStreamingServer[ControlCommand, ControlResponse]) error
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
	GetSlotRange(context.Context, *GetSlotRangeRequest) (*GetSlotRangeResponse, error)
	mustEmbedUnimplementedFumaroleServer()
}

// UnimplementedFumaroleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFumaroleServer struct{}

func (UnimplementedFumaroleServer) GetConsumerGroupInfo(context.Context, *GetConsumerGroupInfoRequest) (*ConsumerGroupInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerGroupInfo not implemented")
}
func (UnimplementedFumaroleServer) ListConsumerGroups(context.Context, *ListConsumerGroupsRequest) (*ListConsumerGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumerGroups not implemented")
}
func (UnimplementedFumaroleServer) DeleteConsumerGroup(context.Context, *DeleteConsumerGroupRequest) (*DeleteConsumerGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConsumerGroup not implemented")
}
func (UnimplementedFumaroleServer) CreateConsumerGroup(context.Context, *CreateConsumerGroupRequest) (*CreateConsumerGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConsumerGroup not implemented")
}
func (UnimplementedFumaroleServer) DownloadBlock(*DownloadBlockShard, grpc.ServerStreamingServer[DataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadBlock not implemented")
}
func (UnimplementedFumaroleServer) SubscribeData(grpc.BidiStreamingServer[DataCommand, DataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeData not implemented")
}
func (UnimplementedFumaroleServer) GetChainTip(context.Context, *GetChainTipRequest) (*GetChainTipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChainTip not implemented")
}
func (UnimplementedFumaroleServer) Subscribe(grpc.BidiStreamingServer[ControlCommand, ControlResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedFumaroleServer) Version(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedFumaroleServer) GetSlotRange(context.Context, *GetSlotRangeRequest) (*GetSlotRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlotRange not implemented")
}
func (UnimplementedFumaroleServer) mustEmbedUnimplementedFumaroleServer() {}
func (UnimplementedFumaroleServer) testEmbeddedByValue()                  {}

// UnsafeFumaroleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FumaroleServer will
// result in compilation errors.
type UnsafeFumaroleServer interface {
	mustEmbedUnimplementedFumaroleServer()
}

func RegisterFumaroleServer(s grpc.ServiceRegistrar, srv FumaroleServer) {
	// If the following call pancis, it indicates UnimplementedFumaroleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fumarole_ServiceDesc, srv)
}

func _Fumarole_GetConsumerGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsumerGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).GetConsumerGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_GetConsumerGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).GetConsumerGroupInfo(ctx, req.(*GetConsumerGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_ListConsumerGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumerGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).ListConsumerGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_ListConsumerGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).ListConsumerGroups(ctx, req.(*ListConsumerGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_DeleteConsumerGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConsumerGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).DeleteConsumerGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_DeleteConsumerGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).DeleteConsumerGroup(ctx, req.(*DeleteConsumerGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_CreateConsumerGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConsumerGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).CreateConsumerGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_CreateConsumerGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).CreateConsumerGroup(ctx, req.(*CreateConsumerGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_DownloadBlock_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBlockShard)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FumaroleServer).DownloadBlock(m, &grpc.GenericServerStream[DownloadBlockShard, DataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_DownloadBlockServer = grpc.ServerStreamingServer[DataResponse]

func _Fumarole_SubscribeData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FumaroleServer).SubscribeData(&grpc.GenericServerStream[DataCommand, DataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_SubscribeDataServer = grpc.BidiStreamingServer[DataCommand, DataResponse]

func _Fumarole_GetChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChainTipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).GetChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_GetChainTip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).GetChainTip(ctx, req.(*GetChainTipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FumaroleServer).Subscribe(&grpc.GenericServerStream[ControlCommand, ControlResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fumarole_SubscribeServer = grpc.BidiStreamingServer[ControlCommand, ControlResponse]

func _Fumarole_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_Version_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fumarole_GetSlotRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSlotRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FumaroleServer).GetSlotRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fumarole_GetSlotRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FumaroleServer).GetSlotRange(ctx, req.(*GetSlotRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fumarole_ServiceDesc is the grpc.ServiceDesc for Fumarole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fumarole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fumarole.Fumarole",
	HandlerType: (*FumaroleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConsumerGroupInfo",
			Handler:    _Fumarole_GetConsumerGroupInfo_Handler,
		},
		{
			MethodName: "ListConsumerGroups",
			Handler:    _Fumarole_ListConsumerGroups_Handler,
		},
		{
			MethodName: "DeleteConsumerGroup",
			Handler:    _Fumarole_DeleteConsumerGroup_Handler,
		},
		{
			MethodName: "CreateConsumerGroup",
			Handler:    _Fumarole_CreateConsumerGroup_Handler,
		},
		{
			MethodName: "GetChainTip",
			Handler:    _Fumarole_GetChainTip_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Fumarole_Version_Handler,
		},
		{
			MethodName: "GetSlotRange",
			Handler:    _Fumarole_GetSlotRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadBlock",
			Handler:       _Fumarole_DownloadBlock_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeData",
			Handler:       _Fumarole_SubscribeData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Fumarole_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fumarole.proto",
}
