// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package meteora_locker

import (
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type AccountsType binary.BorshEnum

const (
	AccountsType_TransferHookEscrow AccountsType = iota
)

func (value AccountsType) String() string {
	switch value {
	case AccountsType_TransferHookEscrow:
		return "TransferHookEscrow"
	default:
		return ""
	}
}

type CreateRootEscrowParameters struct {
	MaxClaimAmount uint64    `json:"maxClaimAmount"`
	MaxEscrow      uint64    `json:"maxEscrow"`
	Version        uint64    `json:"version"`
	Root           [32]uint8 `json:"root"`
}

type CreateVestingEscrowFromRootParams struct {
	VestingStartTime    uint64 `json:"vestingStartTime"`
	CliffTime           uint64 `json:"cliffTime"`
	Frequency           uint64 `json:"frequency"`
	CliffUnlockAmount   uint64 `json:"cliffUnlockAmount"`
	AmountPerPeriod     uint64 `json:"amountPerPeriod"`
	NumberOfPeriod      uint64 `json:"numberOfPeriod"`
	UpdateRecipientMode uint8  `json:"updateRecipientMode"`
	CancelMode          uint8  `json:"cancelMode"`
}

type CreateVestingEscrowMetadataParameters struct {
	Name           string `json:"name"`
	Description    string `json:"description"`
	CreatorEmail   string `json:"creatorEmail"`
	RecipientEmail string `json:"recipientEmail"`
}

type CreateVestingEscrowParameters struct {
	VestingStartTime    uint64 `json:"vestingStartTime"`
	CliffTime           uint64 `json:"cliffTime"`
	Frequency           uint64 `json:"frequency"`
	CliffUnlockAmount   uint64 `json:"cliffUnlockAmount"`
	AmountPerPeriod     uint64 `json:"amountPerPeriod"`
	NumberOfPeriod      uint64 `json:"numberOfPeriod"`
	UpdateRecipientMode uint8  `json:"updateRecipientMode"`
	CancelMode          uint8  `json:"cancelMode"`
}

type EventCancelVestingEscrow struct {
	Escrow          solanago.PublicKey `json:"escrow"`
	Signer          solanago.PublicKey `json:"signer"`
	ClaimableAmount uint64             `json:"claimableAmount"`
	RemainingAmount uint64             `json:"remainingAmount"`
	CancelledAt     uint64             `json:"cancelledAt"`
}

type EventCancelVestingEscrowV3 struct {
	Escrow          solanago.PublicKey `json:"escrow"`
	Signer          solanago.PublicKey `json:"signer"`
	RemainingAmount uint64             `json:"remainingAmount"`
	CancelledAt     uint64             `json:"cancelledAt"`
}

type EventClaim struct {
	Amount    uint64             `json:"amount"`
	CurrentTs uint64             `json:"currentTs"`
	Escrow    solanago.PublicKey `json:"escrow"`
}

type EventClaimV3 struct {
	Amount            uint64             `json:"amount"`
	CurrentTs         uint64             `json:"currentTs"`
	Escrow            solanago.PublicKey `json:"escrow"`
	VestingStartTime  uint64             `json:"vestingStartTime"`
	CliffTime         uint64             `json:"cliffTime"`
	Frequency         uint64             `json:"frequency"`
	CliffUnlockAmount uint64             `json:"cliffUnlockAmount"`
	AmountPerPeriod   uint64             `json:"amountPerPeriod"`
	NumberOfPeriod    uint64             `json:"numberOfPeriod"`
	Recipient         solanago.PublicKey `json:"recipient"`
}
type EventCloseClaimStatus struct {
	Escrow       solanago.PublicKey `json:"escrow"`
	Recipient    solanago.PublicKey `json:"recipient"`
	RentReceiver solanago.PublicKey `json:"rentReceiver"`
}
type EventCloseVestingEscrow struct {
	Escrow solanago.PublicKey `json:"escrow"`
}

type EventCreateRootEscrow struct {
	RootEscrow     solanago.PublicKey `json:"rootEscrow"`
	MaxClaimAmount uint64             `json:"maxClaimAmount"`
	MaxEscrow      uint64             `json:"maxEscrow"`
	Version        uint64             `json:"version"`
	Root           [32]uint8          `json:"root"`
}

type EventCreateVestingEscrow struct {
	VestingStartTime    uint64             `json:"vestingStartTime"`
	CliffTime           uint64             `json:"cliffTime"`
	Frequency           uint64             `json:"frequency"`
	CliffUnlockAmount   uint64             `json:"cliffUnlockAmount"`
	AmountPerPeriod     uint64             `json:"amountPerPeriod"`
	NumberOfPeriod      uint64             `json:"numberOfPeriod"`
	UpdateRecipientMode uint8              `json:"updateRecipientMode"`
	CancelMode          uint8              `json:"cancelMode"`
	Recipient           solanago.PublicKey `json:"recipient"`
	Escrow              solanago.PublicKey `json:"escrow"`
}

type EventFundRootEscrow struct {
	RootEscrow   solanago.PublicKey `json:"rootEscrow"`
	FundedAmount uint64             `json:"fundedAmount"`
}

type EventUpdateVestingEscrowRecipient struct {
	Escrow       solanago.PublicKey `json:"escrow"`
	OldRecipient solanago.PublicKey `json:"oldRecipient"`
	NewRecipient solanago.PublicKey `json:"newRecipient"`
	Signer       solanago.PublicKey `json:"signer"`
}

type RemainingAccountsInfo struct {
	Slices []RemainingAccountsSlice `json:"slices"`
}

type RemainingAccountsSlice struct {
	AccountsType AccountsType `json:"accountsType"`
	Length       uint8        `json:"length"`
}

type RootEscrow struct {
	Discriminator [8]uint8 `json:"discriminator"`
	TokenMint solanago.PublicKey `json:"tokenMint"`
	Creator solanago.PublicKey `json:"creator"`
	Base solanago.PublicKey `json:"base"`
	Root [32]uint8 `json:"root"`
	Bump uint8 `json:"bump"`
	TokenProgramFlag uint8 `json:"tokenProgramFlag"`
	Padding0 [6]uint8 `json:"padding0"`
	MaxClaimAmount uint64 `json:"maxClaimAmount"`
	MaxEscrow uint64 `json:"maxEscrow"`
	TotalFundedAmount uint64 `json:"totalFundedAmount"`
	TotalEscrowCreated uint64 `json:"totalEscrowCreated"`
	TotalDistributeAmount uint64 `json:"totalDistributeAmount"`
	Version uint64 `json:"version"`
	Padding uint64 `json:"padding"`
	Buffer [5]binary.Uint128 `json:"buffer"`
}

type VestingEscrow struct {
	Discriminator [8]uint8 `json:"discriminator"`
	Recipient solanago.PublicKey `json:"recipient"`
	TokenMint solanago.PublicKey `json:"tokenMint"`
	Creator solanago.PublicKey `json:"creator"`
	Base solanago.PublicKey `json:"base"`
	EscrowBump uint8 `json:"escrowBump"`
	UpdateRecipientMode uint8 `json:"updateRecipientMode"`
	CancelMode uint8 `json:"cancelMode"`
	TokenProgramFlag uint8 `json:"tokenProgramFlag"`
	Padding0 [4]uint8 `json:"padding0"`
	CliffTime uint64 `json:"cliffTime"`
	Frequency uint64 `json:"frequency"`
	CliffUnlockAmount uint64 `json:"cliffUnlockAmount"`
	AmountPerPeriod uint64 `json:"amountPerPeriod"`
	NumberOfPeriod uint64 `json:"numberOfPeriod"`
	TotalClaimedAmount uint64 `json:"totalClaimedAmount"`
	VestingStartTime uint64 `json:"vestingStartTime"`
	CancelledAt uint64 `json:"cancelledAt"`
	Padding1 uint64 `json:"padding1"`
	Buffer [5]binary.Uint128 `json:"buffer"`
}

type VestingEscrowMetadata struct {
	Escrow solanago.PublicKey `json:"escrow"`
	Name string `json:"name"`
	Description string `json:"description"`
	CreatorEmail string `json:"creatorEmail"`
	RecipientEmail string `json:"recipientEmail"`
}

