CREATE DATABASE test_api TEMPLATE postgres;
CREATE DATABASE test_comms TEMPLATE postgres;
CREATE DATABASE test_database TEMPLATE postgres;
CREATE DATABASE test_hll TEMPLATE postgres;
CREATE DATABASE test_indexer TEMPLATE postgres;
CREATE DATABASE test_solana_indexer_common TEMPLATE postgres;
CREATE DATABASE test_solana_indexer_token TEMPLATE postgres;
CREATE DATABASE test_solana_indexer_damm_v2 TEMPLATE postgres;
CREATE DATABASE test_solana_indexer_program TEMPLATE postgres;