package api

import (
	"context"
	"log"
	"slices"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	baseRows = map[string]map[string]any{
		"users": {
			"blocknumber":          101,
			"user_id":              nil,
			"handle":               nil,
			"handle_lc":            nil,
			"wallet":               nil,
			"is_current":           true,
			"is_verified":          false,
			"created_at":           time.Now(),
			"updated_at":           time.Now(),
			"has_collectibles":     false,
			"txhash":               "tx1",
			"is_deactivated":       false,
			"is_available":         true,
			"is_storage_v2":        false,
			"allow_ai_attribution": false,
			"profile_type":         nil,
		},
		"tracks": {
			"blocknumber":                           101,
			"blockhash":                             "block_abc123",
			"track_id":                              "@track_id",
			"is_current":                            true,
			"is_delete":                             false,
			"owner_id":                              "@owner_id",
			"title":                                 "@title",
			"genre":                                 "Electronic",
			"mood":                                  "Energetic",
			"created_at":                            time.Now(),
			"updated_at":                            time.Now(),
			"txhash":                                "tx_123abc",
			"is_unlisted":                           false,
			"is_available":                          true,
			"track_segments":                        "[]", // JSONB string
			"is_scheduled_release":                  false,
			"is_downloadable":                       false,
			"is_original_available":                 false,
			"playlists_containing_track":            "{}", // JSONB string
			"playlists_previously_containing_track": map[string]any{},
			"audio_analysis_error_count":            0,
			"is_owned_by_user":                      false,
			"stream_conditions":                     nil,
			"download_conditions":                   nil,
		},
		"playlists": {
			"blocknumber":            101,
			"is_album":               false,
			"is_private":             false,
			"playlist_contents":      "{}",
			"is_current":             true,
			"is_delete":              false,
			"created_at":             time.Now(),
			"updated_at":             time.Now(),
			"txhash":                 "0xabcde12345",
			"is_image_autogenerated": false,
			"is_scheduled_release":   false,
			"stream_conditions":      "{}",
		},
		"follows": {
			"blockhash":        "block1",
			"blocknumber":      101,
			"follower_user_id": nil,
			"followee_user_id": nil,
			"is_current":       true,
			"is_delete":        false,
			"created_at":       time.Now(),
			"txhash":           "tx123",
			"slot":             500,
		},
		"saves": {
			"blockhash":         "block_abc123",
			"blocknumber":       101,
			"user_id":           nil,
			"save_item_id":      nil,
			"save_type":         nil,
			"is_current":        true,
			"is_delete":         false,
			"created_at":        time.Now(),
			"txhash":            "tx_456def",
			"slot":              500,
			"is_save_of_repost": false,
		},
		"reposts": {
			"blockhash":           "block_abc123",
			"blocknumber":         101,
			"user_id":             nil,
			"repost_item_id":      nil,
			"repost_type":         nil,
			"is_current":          true,
			"is_delete":           false,
			"created_at":          time.Now(),
			"txhash":              "tx_456def",
			"slot":                500,
			"is_repost_of_repost": false,
		},
		"developer_apps": {
			"blockhash":   "block1",
			"blocknumber": 101,
			"user_id":     nil,
			"address":     "0x7d7b6b7a97d1deefe3a1ccc5a13c48e8f055e0b6",
			"name":        "Test Developer App",
			"description": "Test Description",
			"created_at":  time.Now(),
			"txhash":      "tx123",
			"is_current":  true,
			"updated_at":  time.Now(),
			"image_url":   nil,
		},
		"track_trending_scores": {
			"track_id":   nil,
			"type":       "TRACKS",
			"genre":      nil,
			"version":    "pnagD",
			"time_range": nil,
			"score":      nil,
			"created_at": time.Now(),
		},
		"playlist_trending_scores": {
			"playlist_id": nil,
			"type":        "PLAYLISTS",
			"version":     "pnagD",
			"time_range":  nil,
			"score":       nil,
			"created_at":  time.Now(),
		},
		"associated_wallets": {
			"id":          nil,
			"user_id":     nil,
			"wallet":      nil,
			"blockhash":   "block_abc123",
			"blocknumber": 101,
			"is_current":  true,
			"is_delete":   false,
			"chain":       nil,
		},
		"aggregate_user_tips": {
			"sender_user_id":   nil,
			"receiver_user_id": nil,
			"amount":           1000,
		},
		"usdc_purchases": {
			"buyer_user_id":  nil,
			"seller_user_id": nil,
			"content_id":     nil,
			"content_type":   "track",
			"amount":         nil,
			"slot":           101,
			"signature":      nil,
			"splits":         "[]",
			"created_at":     time.Now(),
		},
		"grants": {
			"blockhash":       "block1",
			"blocknumber":     101,
			"user_id":         nil,
			"is_current":      true,
			"grantee_address": nil,
			"is_approved":     false,
			"is_revoked":      false,
			"created_at":      time.Now(),
			"updated_at":      time.Now(),
			"txhash":          "tx123",
		},
		"track_routes": {
			"slug":         nil,
			"title_slug":   nil,
			"collision_id": nil,
			"owner_id":     nil,
			"track_id":     nil,
			"is_current":   true,
			"blockhash":    "block_abc123",
			"blocknumber":  101,
			"txhash":       "tx123",
		},
		"playlist_routes": {
			"slug":         nil,
			"title_slug":   nil,
			"collision_id": nil,
			"owner_id":     nil,
			"playlist_id":  nil,
			"is_current":   true,
			"blockhash":    "block_abc123",
			"blocknumber":  101,
			"txhash":       "tx123",
		},
		"playlist_tracks": {
			"created_at": time.Now(),
			"updated_at": time.Now(),
			"is_removed": false,
		},
		"comments": {
			"entity_type": "Track",
			"created_at":  time.Now(),
			"updated_at":  time.Now(),
			"txhash":      "0x1",
			"blockhash":   "0x2",
		},
		"events": {
			"txhash":      "0x1",
			"blockhash":   "0x2",
			"blocknumber": 101,
			"event_id":    nil,
			"entity_type": nil,
			"user_id":     nil,
			"entity_id":   nil,
			"event_type":  nil,
			"end_date":    time.Now().Add(time.Hour * 24 * 30),
			"is_deleted":  false,
			"created_at":  time.Now(),
			"updated_at":  time.Now(),
			"event_data":  nil,
		},
		"user_challenges": {
			"challenge_id":          nil,
			"user_id":               nil,
			"specifier":             nil,
			"is_complete":           nil,
			"current_step_count":    nil,
			"completed_blocknumber": nil,
			"amount":                nil,
			"created_at":            time.Now(),
			"completed_at":          nil,
		},
		"challenge_listen_streak": {
			"user_id":          nil,
			"listen_streak":    nil,
			"last_listen_date": time.Now(),
		},
		"user_bank_accounts": {
			"bank_account":     nil,
			"ethereum_address": nil,
			"created_at":       time.Now(),
			"signature":        nil,
		},
		"audio_transactions_history": {
			"user_bank":              nil,
			"slot":                   101,
			"signature":              nil,
			"transaction_type":       nil,
			"method":                 nil,
			"created_at":             time.Now(),
			"updated_at":             time.Now(),
			"transaction_created_at": time.Now(),
			"tx_metadata":            nil,
			"change":                 0,
			"balance":                0,
		},
		"usdc_user_bank_accounts": {
			"bank_account":     nil,
			"ethereum_address": nil,
			"created_at":       time.Now(),
			"signature":        nil,
		},
		"usdc_transactions_history": {
			"user_bank":              nil,
			"slot":                   101,
			"signature":              nil,
			"transaction_type":       nil,
			"method":                 nil,
			"created_at":             time.Now(),
			"updated_at":             time.Now(),
			"transaction_created_at": time.Now(),
			"tx_metadata":            nil,
			"change":                 0,
			"balance":                0,
		},

		"aggregate_plays":        map[string]any{},
		"aggregate_track":        map[string]any{},
		"aggregate_user":         map[string]any{},
		"challenges":             map[string]any{},
		"comment_threads":        map[string]any{},
		"user_listening_history": map[string]any{},
		"remixes":                map[string]any{},
		"playlist_seen": {
			"user_id":     nil,
			"playlist_id": nil,
			"seen_at":     time.Now(),
			"is_current":  true,
			"blockhash":   "block_abc123",
			"blocknumber": 101,
			"txhash":      "tx_456def",
		},
		"aggregate_monthly_plays": {
			"play_item_id": nil,
			"timestamp":    time.Now(),
			"count":        0,
			"country":      "US",
		},
	}
)

func insertFixturesFromArray(app *ApiServer, table string, data []map[string]any) {

	baseRow, ok := baseRows[table]
	if !ok {
		log.Fatal("no base row for table: ", table)
	}

	// union baseRow keys with data keys for field list
	fieldList := []string{}
	for f := range baseRow {
		fieldList = append(fieldList, f)
	}
	for _, row := range data {
		for f := range row {
			if !slices.Contains(fieldList, f) {
				fieldList = append(fieldList, f)
			}
		}
	}

	var records [][]any
	for _, row := range data {
		thisRow := map[string]any{}
		for field, value := range row {
			if value != nil {
				thisRow[field] = value
			}
		}

		vals := []any{}
		for _, field := range fieldList {
			val := baseRow[field]
			if v, ok := thisRow[field]; ok {
				val = v
			}
			vals = append(vals, val)
		}
		records = append(records, vals)
	}

	_, err := app.pool.CopyFrom(
		context.Background(),
		pgx.Identifier{table},
		fieldList,
		pgx.CopyFromRows(records),
	)
	checkErr(err)
}

func createFixtures(app *ApiServer, fixtures FixtureMap) {

	// the test block must exist...
	_, err := app.pool.Exec(context.Background(), `
	INSERT INTO public.blocks (
		blockhash,
		parenthash,
		is_current,
		number
	) VALUES (
		'block1',   -- blockhash
		'block0',   -- parenthash
		true,
		101
	) ON CONFLICT DO NOTHING;
	`)
	if err != nil {
		panic(err)
	}

	for tableName, rows := range fixtures {
		insertFixturesFromArray(app, tableName, rows)
	}
}
