package api

import (
	"encoding/json"
	"math"
	"strconv"
	"time"

	"api.audius.co/api/dbv1"
	"api.audius.co/indexer"
	"api.audius.co/trashid"
	corev1 "github.com/OpenAudio/go-openaudio/pkg/api/core/v1"
	"github.com/ethereum/go-ethereum/common"
	"github.com/gofiber/fiber/v2"
	"go.uber.org/zap"
)

type PlaylistTrackInfo struct {
	TrackId           string `json:"track_id" validate:"required"`
	Timestamp         int64  `json:"timestamp" validate:"required,min=0"`
	MetadataTimestamp *int64 `json:"metadata_timestamp,omitempty" validate:"omitempty,min=0"`
}

type CreatePlaylistRequest struct {
	PlaylistId                  *trashid.HashId            `json:"playlist_id,omitempty" validate:"omitempty,min=1"`
	PlaylistName                string                     `json:"playlist_name" validate:"required,min=1"`
	Description                 *string                    `json:"description,omitempty" validate:"omitempty,max=1000"`
	IsPrivate                   *bool                      `json:"is_private,omitempty"`
	IsAlbum                     *bool                      `json:"is_album,omitempty"`
	Genre                       *string                    `json:"genre,omitempty" validate:"omitempty,min=1"`
	Mood                        *string                    `json:"mood,omitempty"`
	Tags                        *string                    `json:"tags,omitempty"`
	License                     *string                    `json:"license,omitempty"`
	Upc                         *string                    `json:"upc,omitempty"`
	ReleaseDate                 *string                    `json:"release_date,omitempty"`
	PlaylistImageSizesMultihash *string                    `json:"playlist_image_sizes_multihash,omitempty"`
	PlaylistContents            *[]PlaylistTrackInfo       `json:"playlist_contents,omitempty" validate:"omitempty,dive"`
	DdexApp                     *string                    `json:"ddex_app,omitempty"`
	DdexReleaseIds              *map[string]string         `json:"ddex_release_ids,omitempty"`
	Artists                     *[]DDEXResourceContributor `json:"artists,omitempty" validate:"omitempty,dive"`
	CopyrightLine               *DDEXCopyright             `json:"copyright_line,omitempty" validate:"omitempty"`
	ProducerCopyrightLine       *DDEXCopyright             `json:"producer_copyright_line,omitempty" validate:"omitempty"`
	ParentalWarningType         *string                    `json:"parental_warning_type,omitempty"`
	IsImageAutogenerated        *bool                      `json:"is_image_autogenerated,omitempty"`
	IsStreamGated               *bool                      `json:"is_stream_gated,omitempty"`
	StreamConditions            *AccessConditions          `json:"stream_conditions,omitempty" validate:"omitempty"`
	IsScheduledRelease          *bool                      `json:"is_scheduled_release,omitempty"`
}

type UpdatePlaylistRequest struct {
	PlaylistName                *string                    `json:"playlist_name,omitempty" validate:"omitempty,min=1"`
	Description                 *string                    `json:"description,omitempty" validate:"omitempty,max=1000"`
	IsPrivate                   *bool                      `json:"is_private,omitempty"`
	IsAlbum                     *bool                      `json:"is_album,omitempty"`
	Genre                       *string                    `json:"genre,omitempty" validate:"omitempty,min=1"`
	Mood                        *string                    `json:"mood,omitempty"`
	Tags                        *string                    `json:"tags,omitempty"`
	License                     *string                    `json:"license,omitempty"`
	Upc                         *string                    `json:"upc,omitempty"`
	ReleaseDate                 *string                    `json:"release_date,omitempty"`
	PlaylistImageSizesMultihash *string                    `json:"playlist_image_sizes_multihash,omitempty"`
	PlaylistContents            *[]PlaylistTrackInfo       `json:"playlist_contents,omitempty" validate:"omitempty,dive"`
	DdexApp                     *string                    `json:"ddex_app,omitempty"`
	DdexReleaseIds              *map[string]string         `json:"ddex_release_ids,omitempty"`
	Artists                     *[]DDEXResourceContributor `json:"artists,omitempty" validate:"omitempty,dive"`
	CopyrightLine               *DDEXCopyright             `json:"copyright_line,omitempty" validate:"omitempty"`
	ProducerCopyrightLine       *DDEXCopyright             `json:"producer_copyright_line,omitempty" validate:"omitempty"`
	ParentalWarningType         *string                    `json:"parental_warning_type,omitempty"`
	IsImageAutogenerated        *bool                      `json:"is_image_autogenerated,omitempty"`
	IsStreamGated               *bool                      `json:"is_stream_gated,omitempty"`
	StreamConditions            *AccessConditions          `json:"stream_conditions,omitempty" validate:"omitempty"`
	IsScheduledRelease          *bool                      `json:"is_scheduled_release,omitempty"`
}

func (app *ApiServer) v1Playlist(c *fiber.Ctx) error {
	myId := app.getMyId(c)
	playlistId := c.Locals("playlistId").(int)

	playlists, err := app.queries.Playlists(c.Context(), dbv1.PlaylistsParams{
		GetPlaylistsParams: dbv1.GetPlaylistsParams{
			MyID: myId,
			Ids:  []int32{int32(playlistId)},
		},
	})
	if err != nil {
		return err
	}

	if len(playlists) == 0 {
		return fiber.NewError(fiber.StatusNotFound, "playlist not found")
	}

	playlist := playlists[0]

	return v1PlaylistResponse(c, playlist)
}

func (app *ApiServer) postV1Playlists(c *fiber.Ctx) error {
	userID := app.getMyId(c)

	// Parse and validate request body
	var req CreatePlaylistRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid request body: " + err.Error(),
		})
	}

	// Validate struct tags
	if err := app.requestValidator.Validate(&req); err != nil {
		return err
	}

	// Determine playlist ID
	var playlistID int
	if req.PlaylistId != nil {
		playlistID = int(*req.PlaylistId)
	} else {
		// Generate unclaimed playlist ID if not provided
		generatedID, err := app.generateUnclaimedId(c.Context(), "tracks", "track_id", 400_000, math.MaxInt32)
		if err != nil {
			return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
				"error": "Failed to generate playlist ID: " + err.Error(),
			})
		}
		playlistID = generatedID
	}

	// Convert struct to map for metadata
	metadataBytes, err := json.Marshal(req)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Failed to serialize metadata",
		})
	}

	var metadata map[string]interface{}
	if err := json.Unmarshal(metadataBytes, &metadata); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Failed to process metadata",
		})
	}

	// Remove nil values from metadata
	for key, value := range metadata {
		if value == nil {
			delete(metadata, key)
		}
	}

	signer, err := app.getApiSigner(c)
	if err != nil {
		return err
	}

	nonce := time.Now().UnixNano()

	// Build metadata JSON with cid and data fields
	metadataJSON := map[string]interface{}{
		"cid":  "",
		"data": metadata,
	}
	finalMetadataBytes, _ := json.Marshal(metadataJSON)

	manageEntityTx := &corev1.ManageEntityLegacy{
		Signer:     common.HexToAddress(signer.Address).String(),
		UserId:     int64(userID),
		EntityId:   int64(playlistID),
		Action:     indexer.Action_Create,
		EntityType: indexer.Entity_Playlist,
		Nonce:      strconv.FormatInt(nonce, 10),
		Metadata:   string(finalMetadataBytes),
	}

	response, err := app.sendTransactionWithSigner(manageEntityTx, signer.PrivateKey)
	if err != nil {
		app.logger.Error("Failed to send playlist create transaction", zap.Error(err))
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": "Failed to create playlist",
		})
	}

	encodedPlaylistID, _ := trashid.EncodeHashId(playlistID)
	return c.JSON(fiber.Map{
		"transaction_hash": response.Msg.GetTransaction().GetHash(),
		"block_hash":       response.Msg.GetTransaction().GetBlockHash(),
		"block_number":     response.Msg.GetTransaction().GetHeight(),
		"playlist_id":      encodedPlaylistID,
	})
}

func (app *ApiServer) putV1Playlist(c *fiber.Ctx) error {
	userID := app.getMyId(c)
	playlistID, err := trashid.DecodeHashId(c.Params("playlistId"))
	if err != nil {
		return err
	}

	// Parse and validate request body
	var req UpdatePlaylistRequest
	if err := c.BodyParser(&req); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Invalid request body: " + err.Error(),
		})
	}

	// Validate struct tags
	if err := app.requestValidator.Validate(&req); err != nil {
		return err
	}

	// Convert struct to map for metadata
	metadataBytes, err := json.Marshal(req)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Failed to serialize metadata",
		})
	}

	var metadata map[string]interface{}
	if err := json.Unmarshal(metadataBytes, &metadata); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Failed to process metadata",
		})
	}

	// Remove nil values from metadata
	for key, value := range metadata {
		if value == nil {
			delete(metadata, key)
		}
	}

	// Ensure at least one field is being updated
	if len(metadata) == 0 {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "At least one field must be provided for update",
		})
	}

	signer, err := app.getApiSigner(c)
	if err != nil {
		return err
	}

	nonce := time.Now().UnixNano()

	// Build metadata JSON with cid and data fields
	metadataJSON := map[string]interface{}{
		"cid":  "",
		"data": metadata,
	}
	finalMetadataBytes, _ := json.Marshal(metadataJSON)

	manageEntityTx := &corev1.ManageEntityLegacy{
		Signer:     common.HexToAddress(signer.Address).String(),
		UserId:     int64(userID),
		EntityId:   int64(playlistID),
		Action:     indexer.Action_Update,
		EntityType: indexer.Entity_Playlist,
		Nonce:      strconv.FormatInt(nonce, 10),
		Metadata:   string(finalMetadataBytes),
	}

	response, err := app.sendTransactionWithSigner(manageEntityTx, signer.PrivateKey)
	if err != nil {
		app.logger.Error("Failed to send playlist update transaction", zap.Error(err))
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": "Failed to update playlist",
		})
	}

	return c.JSON(fiber.Map{
		"transaction_hash": response.Msg.GetTransaction().GetHash(),
		"block_hash":       response.Msg.GetTransaction().GetBlockHash(),
		"block_number":     response.Msg.GetTransaction().GetHeight(),
	})
}

func (app *ApiServer) deleteV1Playlist(c *fiber.Ctx) error {
	userID := app.getMyId(c)
	playlistID, err := trashid.DecodeHashId(c.Params("playlistId"))
	if err != nil {
		return err
	}

	signer, err := app.getApiSigner(c)
	if err != nil {
		return err
	}

	nonce := time.Now().UnixNano()

	manageEntityTx := &corev1.ManageEntityLegacy{
		Signer:     common.HexToAddress(signer.Address).String(),
		UserId:     int64(userID),
		EntityId:   int64(playlistID),
		Action:     indexer.Action_Delete,
		EntityType: indexer.Entity_Playlist,
		Nonce:      strconv.FormatInt(nonce, 10),
		Metadata:   "",
	}

	response, err := app.sendTransactionWithSigner(manageEntityTx, signer.PrivateKey)
	if err != nil {
		app.logger.Error("Failed to send playlist delete transaction", zap.Error(err))
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error": "Failed to delete playlist",
		})
	}

	return c.JSON(fiber.Map{
		"transaction_hash": response.Msg.GetTransaction().GetHash(),
		"block_hash":       response.Msg.GetTransaction().GetBlockHash(),
		"block_number":     response.Msg.GetTransaction().GetHeight(),
	})
}
