name: Build and Push Docker Image

on:
  push:
    branches: [ '**' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get full SHA
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            audius/api:latest,enable=${{ github.ref == 'refs/heads/main' }}
            audius/api:${{ steps.sha.outputs.sha }}
          cache-from: type=registry,ref=audius/api:buildcache
          cache-to: type=registry,ref=audius/api:buildcache,mode=max 