ame: Build, Push, and Deploy

on:
  push:
    branches: [main]

jobs:
  - name: Checkout audius-k8s repo
    uses: actions/checkout@v4
    with:
      repository: audiusproject/audius-k8s
      path: audius-k8s
      token: ${{ secrets.GITHUB_TOKEN }}

  - name: Set up Pulumi
    uses: pulumi/actions@v4

  - name: Up build stack
    run: |
      cd audius-k8s
      pulumi stack select audius/build-api
      pulumi up --yes

  - name: Up stage stack
    run: |
      cd audius-k8s
      pulumi stack select audius/stage-api
      pulumi up --yes
