ame: Build, Push, and Deploy

on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout audius-k8s repo
        uses: actions/checkout@v4
        with:
          repository: audiusproject/audius-k8s
          path: audius-k8s
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: go mod download

      - name: Up build stack
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: audius/audius-k8s/build-api
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Up stage stack
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: audius/audius-k8s/stage-api
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
