// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exists.sql

package dbv1

import (
	"context"

	"api.audius.co/trashid"
)

const developerAppExists = `-- name: DeveloperAppExists :one
SELECT EXISTS(
  SELECT 1
  FROM developer_apps
  WHERE 
    address = lower($1)
    AND is_current = true
    AND is_delete = false
)
`

func (q *Queries) DeveloperAppExists(ctx context.Context, address string) (bool, error) {
	row := q.db.QueryRow(ctx, developerAppExists, address)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const grantExists = `-- name: GrantExists :one
SELECT EXISTS(
  SELECT 1
  FROM grants
  WHERE 
    user_id = $1
    AND grantee_address = lower($2)
    AND is_current = true
    AND is_revoked = false
)
`

type GrantExistsParams struct {
	UserID         trashid.HashId `json:"user_id"`
	GranteeAddress string         `json:"grantee_address"`
}

func (q *Queries) GrantExists(ctx context.Context, arg GrantExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, grantExists, arg.UserID, arg.GranteeAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(
  SELECT 1
  FROM users
  WHERE 
    wallet = lower($1)
    AND is_current = true
    AND is_deactivated = false
)
`

func (q *Queries) UserExists(ctx context.Context, wallet string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, wallet)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
