// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_extended_account_fields.sql

package dbv1

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExtendedAccountFields = `-- name: GetExtendedAccountFields :one
SELECT
  track_save_count
FROM aggregate_user
WHERE user_id = $1
`

func (q *Queries) GetExtendedAccountFields(ctx context.Context, userID int32) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, getExtendedAccountFields, userID)
	var track_save_count pgtype.Int8
	err := row.Scan(&track_save_count)
	return track_save_count, err
}
