// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_developer_apps.sql

package dbv1

import (
	"context"
	"time"

	"api.audius.co/trashid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeveloperApps = `-- name: GetDeveloperApps :many
SELECT
  da.address,
  da.user_id,
  da.name,
  da.description,
  da.image_url,
  COALESCE(ARRAY_AGG(oau.redirect_uri ORDER BY oau.id) FILTER (WHERE oau.redirect_uri IS NOT NULL), ARRAY[]::text[])::text[] AS redirect_uris
FROM developer_apps da
LEFT JOIN oauth_redirect_uris oau ON oau.client_id = da.address
WHERE
  (da.user_id = $1 OR da.address = $2)
  AND da.is_current = true
  AND da.is_delete = false
GROUP BY da.address, da.user_id, da.name, da.description, da.image_url, da.created_at
ORDER BY da.created_at DESC
`

type GetDeveloperAppsParams struct {
	UserID  trashid.HashId `json:"user_id"`
	Address string         `json:"address"`
}

type GetDeveloperAppsRow struct {
	Address      string         `json:"address"`
	UserID       trashid.HashId `json:"user_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	ImageUrl     pgtype.Text    `json:"image_url"`
	RedirectUris []string       `json:"redirect_uris"`
}

func (q *Queries) GetDeveloperApps(ctx context.Context, arg GetDeveloperAppsParams) ([]GetDeveloperAppsRow, error) {
	rows, err := q.db.Query(ctx, getDeveloperApps, arg.UserID, arg.Address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeveloperAppsRow
	for rows.Next() {
		var i GetDeveloperAppsRow
		if err := rows.Scan(
			&i.Address,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.RedirectUris,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeveloperAppsWithGrants = `-- name: GetDeveloperAppsWithGrants :many
SELECT
  developer_apps.address,
  developer_apps.name,
  developer_apps.description,
  developer_apps.image_url,
  grants.user_id AS grantor_user_id,
  grants.created_at AS grant_created_at,
  grants.updated_at AS grant_updated_at
FROM developer_apps
LEFT JOIN grants ON grants.grantee_address = developer_apps.address
WHERE
  (grants.user_id = $1 OR developer_apps.address = $2)
  AND grants.is_revoked = false
  AND grants.is_current = true
  AND developer_apps.is_current = true
  AND developer_apps.is_delete = false
ORDER BY grants.updated_at ASC
`

type GetDeveloperAppsWithGrantsParams struct {
	UserID  trashid.HashId `json:"user_id"`
	Address string         `json:"address"`
}

type GetDeveloperAppsWithGrantsRow struct {
	Address        string         `json:"address"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	ImageUrl       pgtype.Text    `json:"image_url"`
	GrantorUserID  trashid.HashId `json:"grantor_user_id"`
	GrantCreatedAt *time.Time     `json:"grant_created_at"`
	GrantUpdatedAt *time.Time     `json:"grant_updated_at"`
}

func (q *Queries) GetDeveloperAppsWithGrants(ctx context.Context, arg GetDeveloperAppsWithGrantsParams) ([]GetDeveloperAppsWithGrantsRow, error) {
	rows, err := q.db.Query(ctx, getDeveloperAppsWithGrants, arg.UserID, arg.Address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeveloperAppsWithGrantsRow
	for rows.Next() {
		var i GetDeveloperAppsWithGrantsRow
		if err := rows.Scan(
			&i.Address,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.GrantorUserID,
			&i.GrantCreatedAt,
			&i.GrantUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
