// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_sitemap.sql

package dbv1

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSitemapPlaylistCount = `-- name: GetSitemapPlaylistCount :one
SELECT count(*) as count
FROM playlist_routes pr
JOIN playlists p ON pr.playlist_id = p.playlist_id
JOIN users u ON pr.owner_id = u.user_id
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE u.is_current = true
  AND pr.is_current = true
  AND p.is_current = true
  AND p.is_private = false
  AND p.is_delete = false
  AND au.follower_count >= 10
`

func (q *Queries) GetSitemapPlaylistCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSitemapPlaylistCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSitemapPlaylistSlugs = `-- name: GetSitemapPlaylistSlugs :many
SELECT u.handle, pr.slug, p.is_album
FROM playlist_routes pr
JOIN playlists p ON pr.playlist_id = p.playlist_id
JOIN users u ON pr.owner_id = u.user_id
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE u.is_current = true
  AND pr.is_current = true
  AND p.is_current = true
  AND p.is_private = false
  AND p.is_delete = false
  AND au.follower_count >= 10
ORDER BY p.playlist_id ASC
LIMIT $1 OFFSET $2
`

type GetSitemapPlaylistSlugsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetSitemapPlaylistSlugsRow struct {
	Handle  pgtype.Text `json:"handle"`
	Slug    string      `json:"slug"`
	IsAlbum bool        `json:"is_album"`
}

func (q *Queries) GetSitemapPlaylistSlugs(ctx context.Context, arg GetSitemapPlaylistSlugsParams) ([]GetSitemapPlaylistSlugsRow, error) {
	rows, err := q.db.Query(ctx, getSitemapPlaylistSlugs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSitemapPlaylistSlugsRow
	for rows.Next() {
		var i GetSitemapPlaylistSlugsRow
		if err := rows.Scan(&i.Handle, &i.Slug, &i.IsAlbum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSitemapTrackCount = `-- name: GetSitemapTrackCount :one
SELECT count(*) as count
FROM track_routes tr
JOIN tracks t ON tr.track_id = t.track_id
JOIN users u ON tr.owner_id = u.user_id
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE t.is_current = true
  AND t.stem_of IS NULL
  AND t.is_unlisted = false
  AND t.is_available = true
  AND t.is_delete = false
  AND u.is_current = true
  AND tr.is_current = true
  AND au.follower_count >= 10
`

func (q *Queries) GetSitemapTrackCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSitemapTrackCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSitemapTrackSlugs = `-- name: GetSitemapTrackSlugs :many
SELECT u.handle, tr.slug
FROM track_routes tr
JOIN tracks t ON tr.track_id = t.track_id
JOIN users u ON tr.owner_id = u.user_id
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE t.is_current = true
  AND t.stem_of IS NULL
  AND t.is_unlisted = false
  AND t.is_available = true
  AND t.is_delete = false
  AND u.is_current = true
  AND tr.is_current = true
  AND au.follower_count >= 10
ORDER BY t.track_id ASC
LIMIT $1 OFFSET $2
`

type GetSitemapTrackSlugsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetSitemapTrackSlugsRow struct {
	Handle pgtype.Text `json:"handle"`
	Slug   string      `json:"slug"`
}

func (q *Queries) GetSitemapTrackSlugs(ctx context.Context, arg GetSitemapTrackSlugsParams) ([]GetSitemapTrackSlugsRow, error) {
	rows, err := q.db.Query(ctx, getSitemapTrackSlugs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSitemapTrackSlugsRow
	for rows.Next() {
		var i GetSitemapTrackSlugsRow
		if err := rows.Scan(&i.Handle, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSitemapUserCount = `-- name: GetSitemapUserCount :one
SELECT count(*) as count
FROM users u
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE u.is_current = true
  AND u.is_deactivated = false
  AND u.handle_lc IS NOT NULL
  AND u.is_available = true
  AND au.follower_count >= 10
`

func (q *Queries) GetSitemapUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSitemapUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSitemapUserSlugs = `-- name: GetSitemapUserSlugs :many
SELECT u.handle
FROM users u
JOIN aggregate_user au ON u.user_id = au.user_id
WHERE u.is_current = true
  AND u.is_deactivated = false
  AND u.handle_lc IS NOT NULL
  AND u.is_available = true
  AND au.follower_count >= 10
ORDER BY u.user_id ASC
LIMIT $1 OFFSET $2
`

type GetSitemapUserSlugsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSitemapUserSlugs(ctx context.Context, arg GetSitemapUserSlugsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getSitemapUserSlugs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var handle pgtype.Text
		if err := rows.Scan(&handle); err != nil {
			return nil, err
		}
		items = append(items, handle)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
