// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_for_handle.sql

package dbv1

import (
	"context"

	"bridgerton.audius.co/trashid"
)

const getUserForHandle = `-- name: GetUserForHandle :one
SELECT user_id FROM users
WHERE
    handle_lc = lower($1)
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetUserForHandle(ctx context.Context, handle string) (trashid.HashId, error) {
	row := q.db.QueryRow(ctx, getUserForHandle, handle)
	var user_id trashid.HashId
	err := row.Scan(&user_id)
	return user_id, err
}
