// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_track_download_counts.sql

package dbv1

import (
	"context"
)

const getTrackDownloadCounts = `-- name: GetTrackDownloadCounts :many
SELECT
  t.track_id,
  (
    SELECT count(*)::bigint
    FROM track_downloads d
    WHERE (t.stem_of IS NOT NULL
           AND d.parent_track_id = (t.stem_of->>'parent_track_id')::int
           AND d.track_id = t.track_id)
       OR (t.stem_of IS NULL AND d.parent_track_id = t.track_id)
  ) AS download_count
FROM tracks t
WHERE t.track_id = ANY($1::int[])
  AND t.is_current = true
  AND t.is_delete = false
`

type GetTrackDownloadCountsRow struct {
	TrackID       int32 `json:"track_id"`
	DownloadCount int64 `json:"download_count"`
}

func (q *Queries) GetTrackDownloadCounts(ctx context.Context, trackIds []int32) ([]GetTrackDownloadCountsRow, error) {
	rows, err := q.db.Query(ctx, getTrackDownloadCounts, trackIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackDownloadCountsRow
	for rows.Next() {
		var i GetTrackDownloadCountsRow
		if err := rows.Scan(&i.TrackID, &i.DownloadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
