// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user_for_wallet.sql

package dbv1

import (
	"context"

	"bridgerton.audius.co/trashid"
)

const getUserForWallet = `-- name: GetUserForWallet :one
SELECT user_id FROM users
WHERE
    wallet = lower($1)
    AND is_current = true
ORDER BY handle IS NOT NULL, created_at ASC
LIMIT 1
`

func (q *Queries) GetUserForWallet(ctx context.Context, wallet string) (trashid.HashId, error) {
	row := q.db.QueryRow(ctx, getUserForWallet, wallet)
	var user_id trashid.HashId
	err := row.Scan(&user_id)
	return user_id, err
}
