// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_playlist_ids_by_permalink.sql

package dbv1

import (
	"context"
)

const getPlaylistIdsByPermalink = `-- name: GetPlaylistIdsByPermalink :many
SELECT playlist_id
FROM playlist_routes
JOIN users ON users.user_id = playlist_routes.owner_id
WHERE handle_lc = ANY($1::text[])
    AND slug = ANY($2::text[])
    AND (
        CONCAT(handle_lc, '/playlist/', slug) = ANY($3::text[]) -- in case of conflicts across users
        OR CONCAT(handle_lc, '/album/', slug) = ANY($3::text[]) -- in case of conflicts across users
    )
`

type GetPlaylistIdsByPermalinkParams struct {
	Handles    []string `json:"handles"`
	Slugs      []string `json:"slugs"`
	Permalinks []string `json:"permalinks"`
}

func (q *Queries) GetPlaylistIdsByPermalink(ctx context.Context, arg GetPlaylistIdsByPermalinkParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getPlaylistIdsByPermalink, arg.Handles, arg.Slugs, arg.Permalinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var playlist_id int32
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
