// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_track_download_count_total.sql

package dbv1

import (
	"context"
)

const getUserTrackDownloadCountTotal = `-- name: GetUserTrackDownloadCountTotal :one
SELECT count(*)::bigint AS total_download_count
FROM track_downloads d
WHERE EXISTS (
  SELECT 1
  FROM tracks t
  WHERE t.owner_id = $1
    AND t.is_current = true
    AND t.is_delete = false
    AND d.track_id = t.track_id
    AND (
      (t.stem_of IS NULL AND d.parent_track_id = t.track_id)
      OR (t.stem_of IS NOT NULL
          AND (t.stem_of->>'parent_track_id')::int = d.parent_track_id)
    )
)
`

// Total download count for all tracks (and stems) owned by the user.
// Each download event is counted once.
func (q *Queries) GetUserTrackDownloadCountTotal(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUserTrackDownloadCountTotal, userID)
	var total_download_count int64
	err := row.Scan(&total_download_count)
	return total_download_count, err
}
