// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_genre_metrics.sql

package dbv1

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGenreMetrics = `-- name: GetGenreMetrics :many
SELECT
    genre,
    COUNT(track_id) AS count
FROM
    tracks
WHERE
    genre IS NOT NULL
    AND genre != ''
    AND is_current = TRUE
    AND created_at > $1
GROUP BY
    genre
ORDER BY
    count DESC
LIMIT $3
OFFSET $2
`

type GetGenreMetricsParams struct {
	StartTime time.Time `json:"start_time"`
	OffsetVal int32     `json:"offset_val"`
	LimitVal  int32     `json:"limit_val"`
}

type GetGenreMetricsRow struct {
	Genre pgtype.Text `json:"genre"`
	Count int64       `json:"count"`
}

func (q *Queries) GetGenreMetrics(ctx context.Context, arg GetGenreMetricsParams) ([]GetGenreMetricsRow, error) {
	rows, err := q.db.Query(ctx, getGenreMetrics, arg.StartTime, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGenreMetricsRow
	for rows.Next() {
		var i GetGenreMetricsRow
		if err := rows.Scan(&i.Genre, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
