// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_playlist_ids_by_permalink.sql

package dbv1

import (
	"context"
)

const getPlaylistIdsByPermalink = `-- name: GetPlaylistIdsByPermalink :many
WITH lower_handles AS (
  SELECT LOWER(h) AS handle
  FROM unnest($2::text[]) AS h
),
lower_permalinks AS (
  SELECT LOWER(p) AS permalink
  FROM unnest($3::text[]) AS p
)
SELECT pr.playlist_id
FROM playlist_routes pr
JOIN users u ON u.user_id = pr.owner_id
JOIN lower_handles lh
  ON u.handle_lc = lh.handle
WHERE pr.slug = ANY($1::text[])
  -- in case of conflicts across users
  AND (
    CONCAT('/', u.handle_lc, '/playlist/', LOWER(pr.slug)) = ANY(
      SELECT permalink FROM lower_permalinks
    )
    OR CONCAT('/', u.handle_lc, '/album/', LOWER(pr.slug)) = ANY(
      SELECT permalink FROM lower_permalinks
    )
  )
`

type GetPlaylistIdsByPermalinkParams struct {
	Slugs      []string `json:"slugs"`
	Handles    []string `json:"handles"`
	Permalinks []string `json:"permalinks"`
}

func (q *Queries) GetPlaylistIdsByPermalink(ctx context.Context, arg GetPlaylistIdsByPermalinkParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getPlaylistIdsByPermalink, arg.Slugs, arg.Handles, arg.Permalinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var playlist_id int32
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
