// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_aggregate_route_metrics.sql

package dbv1

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAggregateRouteMetrics = `-- name: GetAggregateRouteMetrics :many
WITH week_unique_daily AS (
    SELECT 
        timestamp,
        count AS unique_count,
        summed_count AS summed_unique_count
    FROM 
        aggregate_daily_unique_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '7 days'
        AND timestamp < CURRENT_DATE
),
week_total_daily AS (
    SELECT 
        timestamp,
        count AS total_count
    FROM 
        aggregate_daily_total_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '7 days'
        AND timestamp < CURRENT_DATE
),
month_unique_daily AS (
    SELECT 
        timestamp,
        count AS unique_count,
        summed_count AS summed_unique_count
    FROM 
        aggregate_daily_unique_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '30 days'
        AND timestamp < CURRENT_DATE
),
month_total_daily AS (
    SELECT 
        timestamp,
        count AS total_count
    FROM 
        aggregate_daily_total_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '30 days'
        AND timestamp < CURRENT_DATE
),
month_unique_weekly AS (
    SELECT 
        date_trunc('week', timestamp)::timestamp as timestamp,
        SUM(count) AS unique_count,
        SUM(summed_count) AS summed_unique_count
    FROM 
        aggregate_daily_unique_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '30 days'
        AND timestamp < CURRENT_DATE
    GROUP BY 
        date_trunc('week', timestamp)
),
month_total_weekly AS (
    SELECT 
        date_trunc('week', timestamp)::timestamp as timestamp,
        SUM(count) AS total_count
    FROM 
        aggregate_daily_total_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '30 days'
        AND timestamp < CURRENT_DATE
    GROUP BY 
        date_trunc('week', timestamp)
),
year_unique_monthly AS (
    SELECT 
        timestamp,
        count AS unique_count,
        summed_count AS summed_unique_count
    FROM 
        aggregate_monthly_unique_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '365 days'
        AND timestamp < date_trunc('month', CURRENT_DATE)
),
year_total_monthly AS (
    SELECT 
        timestamp,
        count AS total_count
    FROM 
        aggregate_monthly_total_users_metrics
    WHERE 
        timestamp >= CURRENT_DATE - INTERVAL '365 days'
        AND timestamp < date_trunc('month', CURRENT_DATE)
),
alltime_unique_monthly AS (
    SELECT 
        timestamp,
        count AS unique_count,
        summed_count AS summed_unique_count
    FROM 
        aggregate_monthly_unique_users_metrics
    WHERE 
        timestamp < date_trunc('month', CURRENT_DATE)
),
alltime_total_monthly AS (
    SELECT 
        timestamp,
        count AS total_count
    FROM 
        aggregate_monthly_total_users_metrics
    WHERE 
        timestamp < date_trunc('month', CURRENT_DATE)
),
alltime_unique_weekly AS (
    SELECT 
        date_trunc('week', timestamp)::timestamp as timestamp,
        SUM(count) AS unique_count,
        SUM(summed_count) AS summed_unique_count
    FROM 
        aggregate_daily_unique_users_metrics
    WHERE 
        timestamp < CURRENT_DATE
    GROUP BY 
        date_trunc('week', timestamp)
),
alltime_total_weekly AS (
    SELECT 
        date_trunc('week', timestamp)::timestamp as timestamp,
        SUM(count) AS total_count
    FROM 
        aggregate_daily_total_users_metrics
    WHERE 
        timestamp < CURRENT_DATE
    GROUP BY 
        date_trunc('week', timestamp)
),
result_data AS (
    -- Week with day bucket size
    SELECT 
        w_unique.timestamp,
        w_unique.unique_count,
        w_unique.summed_unique_count,
        w_total.total_count
    FROM 
        week_unique_daily w_unique
    JOIN 
        week_total_daily w_total 
    ON 
        w_unique.timestamp = w_total.timestamp
    WHERE 
        $1 = 'week' AND $2 = 'day'
    
    UNION ALL
    
    -- Month with day bucket size
    SELECT 
        m_unique.timestamp,
        m_unique.unique_count,
        m_unique.summed_unique_count,
        m_total.total_count
    FROM 
        month_unique_daily m_unique
    JOIN 
        month_total_daily m_total 
    ON 
        m_unique.timestamp = m_total.timestamp
    WHERE 
        $1 = 'month' AND $2 = 'day'
    
    UNION ALL
    
    -- Month with week bucket size
    SELECT 
        m_unique.timestamp,
        m_unique.unique_count,
        m_unique.summed_unique_count,
        m_total.total_count
    FROM 
        month_unique_weekly m_unique
    JOIN 
        month_total_weekly m_total 
    ON 
        m_unique.timestamp = m_total.timestamp
    WHERE 
        $1 = 'month' AND $2 = 'week'
    
    UNION ALL
    
    -- Year with month bucket size
    SELECT 
        y_unique.timestamp,
        y_unique.unique_count,
        y_unique.summed_unique_count,
        y_total.total_count
    FROM 
        year_unique_monthly y_unique
    JOIN 
        year_total_monthly y_total 
    ON 
        y_unique.timestamp = y_total.timestamp
    WHERE 
        $1 = 'year' AND $2 = 'month'
    
    UNION ALL
    
    -- All time with month bucket size
    SELECT 
        a_unique.timestamp,
        a_unique.unique_count,
        a_unique.summed_unique_count,
        a_total.total_count
    FROM 
        alltime_unique_monthly a_unique
    JOIN 
        alltime_total_monthly a_total 
    ON 
        a_unique.timestamp = a_total.timestamp
    WHERE 
        $1 = 'all_time' AND $2 = 'month'
    
    UNION ALL
    
    -- All time with week bucket size
    SELECT 
        a_unique.timestamp,
        a_unique.unique_count,
        a_unique.summed_unique_count,
        a_total.total_count
    FROM 
        alltime_unique_weekly a_unique
    JOIN 
        alltime_total_weekly a_total 
    ON 
        a_unique.timestamp = a_total.timestamp
    WHERE 
        $1 = 'all_time' AND $2 = 'week'
)
SELECT 
    -- Return the date as a formatted string in YYYY-MM-DD format
    to_char(date_trunc('month', timestamp)::date, 'YYYY-MM-DD') AS timestamp,
    unique_count,
    summed_unique_count,
    total_count
FROM 
    result_data
ORDER BY 
    timestamp ASC
`

type GetAggregateRouteMetricsParams struct {
	TimeRange  interface{} `json:"time_range"`
	BucketSize interface{} `json:"bucket_size"`
}

type GetAggregateRouteMetricsRow struct {
	Timestamp         string      `json:"timestamp"`
	UniqueCount       int32       `json:"unique_count"`
	SummedUniqueCount pgtype.Int4 `json:"summed_unique_count"`
	TotalCount        int32       `json:"total_count"`
}

// Use to_char to format dates consistently as YYYY-MM-DD
func (q *Queries) GetAggregateRouteMetrics(ctx context.Context, arg GetAggregateRouteMetricsParams) ([]GetAggregateRouteMetricsRow, error) {
	rows, err := q.db.Query(ctx, getAggregateRouteMetrics, arg.TimeRange, arg.BucketSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregateRouteMetricsRow
	for rows.Next() {
		var i GetAggregateRouteMetricsRow
		if err := rows.Scan(
			&i.Timestamp,
			&i.UniqueCount,
			&i.SummedUniqueCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
