// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_events.sql

package dbv1

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvents = `-- name: GetEvents :many
SELECT
  e.event_id AS event_id,
  e.entity_type::event_entity_type AS entity_type,
  e.user_id AS user_id,
  e.entity_id AS entity_id,
  e.event_type::event_type AS event_type,
  e.end_date AS end_date,
  e.is_deleted AS is_deleted,
  e.created_at AS created_at,
  e.updated_at AS updated_at,
  e.event_data AS event_data
FROM events e
LEFT JOIN tracks t ON t.track_id = e.entity_id AND t.is_current = true AND e.entity_type = 'track'
  AND (t.access_authorities IS NULL OR t.access_authorities = '{}')
WHERE
  ($1::int[] = '{}' OR e.entity_id = ANY($1::int[]))
  AND ($2::int[] = '{}' OR e.event_id = ANY($2::int[]))
  AND ($3::text = '' OR e.entity_type = $3::event_entity_type)
  AND ($4::text = '' OR e.event_type = $4::event_type)
  AND ($5::boolean IS NULL OR e.is_deleted = $5)
  AND (e.entity_type != 'track' OR (t.track_id IS NOT NULL AND t.is_delete = false))
ORDER BY e.created_at DESC, e.event_id ASC
LIMIT $7
OFFSET $6
`

type GetEventsParams struct {
	EntityIds     []int32 `json:"entity_ids"`
	EventIds      []int32 `json:"event_ids"`
	EntityType    string  `json:"entity_type"`
	EventType     string  `json:"event_type"`
	FilterDeleted bool    `json:"filter_deleted"`
	OffsetVal     int32   `json:"offset_val"`
	LimitVal      int32   `json:"limit_val"`
}

type GetEventsRow struct {
	EventID    int32           `json:"event_id"`
	EntityType EventEntityType `json:"entity_type"`
	UserID     int32           `json:"user_id"`
	EntityID   pgtype.Int4     `json:"entity_id"`
	EventType  EventType       `json:"event_type"`
	EndDate    *time.Time      `json:"end_date"`
	IsDeleted  pgtype.Bool     `json:"is_deleted"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
	EventData  *EventData      `json:"event_data"`
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]GetEventsRow, error) {
	rows, err := q.db.Query(ctx, getEvents,
		arg.EntityIds,
		arg.EventIds,
		arg.EntityType,
		arg.EventType,
		arg.FilterDeleted,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsRow
	for rows.Next() {
		var i GetEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.EntityType,
			&i.UserID,
			&i.EntityID,
			&i.EventType,
			&i.EndDate,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EventData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
