// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_track_ids_by_isrc.sql

package dbv1

import (
	"context"
)

const getTrackIdsByISRC = `-- name: GetTrackIdsByISRC :many
SELECT track_id
FROM tracks
WHERE isrc = ANY($1::text[])
`

func (q *Queries) GetTrackIdsByISRC(ctx context.Context, isrcs []string) ([]int32, error) {
	rows, err := q.db.Query(ctx, getTrackIdsByISRC, isrcs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var track_id int32
		if err := rows.Scan(&track_id); err != nil {
			return nil, err
		}
		items = append(items, track_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
