// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_users.sql

package dbv1

import (
	"context"
	"encoding/json"
	"time"

	"api.audius.co/trashid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUsers = `-- name: GetUsers :many
WITH input_users AS (
  SELECT DISTINCT unnest($2::int[])::int AS user_id
),
current_user_followees AS (
  SELECT followee_user_id
  FROM follows
  WHERE $1 > 0
    AND follower_user_id = $1
    AND is_delete = false
),
current_user_following_targets AS (
  SELECT f.followee_user_id AS user_id
  FROM follows f
  JOIN input_users i ON i.user_id = f.followee_user_id
  WHERE $1 > 0
    AND f.follower_user_id = $1
    AND f.is_delete = false
  GROUP BY f.followee_user_id
),
current_user_subscribed_targets AS (
  SELECT s.user_id
  FROM subscriptions s
  JOIN input_users i ON i.user_id = s.user_id
  WHERE $1 > 0
    AND s.entity_type = 'User'
    AND s.subscriber_id = $1
    AND s.is_delete = false
  GROUP BY s.user_id
),
targets_following_current_user AS (
  SELECT f.follower_user_id AS user_id
  FROM follows f
  JOIN input_users i ON i.user_id = f.follower_user_id
  WHERE $1 > 0
    AND f.followee_user_id = $1
    AND f.is_delete = false
  GROUP BY f.follower_user_id
),
current_user_followee_follow_counts AS (
  SELECT target.user_id, count(*)::bigint AS count
  FROM current_user_followees mf
  JOIN LATERAL (
    SELECT f.followee_user_id AS user_id
    FROM follows f
    WHERE f.follower_user_id = mf.followee_user_id
      AND f.followee_user_id = ANY($2::int[])
      AND f.followee_user_id != $1
      AND f.is_delete = false
    OFFSET 0
  ) target ON TRUE
  GROUP BY target.user_id
)
SELECT
  album_count,
  artist_pick_track_id,
  bio,

  -- todo: this can sometimes be a Qm cid
  -- sometimes be a json string...
  cover_photo,

  follower_count,
  following_count as followee_count,
  handle,
  u.user_id as id,
  u.user_id::int as user_id,
  is_verified,
  twitter_handle,
  instagram_handle,
  tiktok_handle,
  verified_with_twitter,
  verified_with_instagram,
  verified_with_tiktok,
  website,
  donation,
  location,
  name,
  playlist_count,
  profile_type,

  -- todo: this can sometimes be a Qm cid
  -- sometimes be a json string...
  profile_picture,

  repost_count,
  -- Use total_track_count when viewing own profile, otherwise use track_count
  (CASE
    WHEN u.user_id = $1::int THEN total_track_count
    ELSE track_count
  END)::bigint as track_count,
  is_deactivated,
  is_available,
  wallet as erc_wallet,
  spl_user_bank.account as spl_wallet,
  usdc_user_bank.account as usdc_wallet,
  spl_usdc_payout_wallet,
  supporter_count,
  supporting_count,
  wallet,

  -- Legacy ` + "`" + `balance` + "`" + ` (ETH-side AUDIO in wei) and ` + "`" + `associated_wallets_balance` + "`" + `
  -- (the split between primary and linked wallets) are collapsed into
  -- v_user_balances.eth_balance — sol_user_balances doesn't preserve a
  -- user_bank-vs-linked breakdown so we don't preserve one on the ETH side
  -- either. Surface the full ETH total under ` + "`" + `balance` + "`" + ` and zero out
  -- ` + "`" + `associated_wallets_balance` + "`" + ` so the response shape stays the same and
  -- ` + "`" + `total_balance` + "`" + ` still adds up to the right number.
  coalesce(eth_balance, '0') as balance,
  '0' as associated_wallets_balance,

  -- total_balance: eth_balance is in wei, sol_balance is in wAUDIO base units
  -- (8 decimals) so multiply by 10^10 to convert.
  (
    coalesce(eth_balance, '0')::NUMERIC +
    (coalesce(sol_balance, '0')::NUMERIC * 10^10)
  )::NUMERIC::TEXT AS total_balance,

  -- total_audio_balance,
  FLOOR(
    (
      coalesce(eth_balance, '0')::NUMERIC +
      (coalesce(sol_balance, '0')::NUMERIC * 10^10)
    ) / 1e18
  )::INT AS total_audio_balance,

  -- payout wallet
  coalesce(
    spl_usdc_payout_wallet,
    usdc_user_bank.account,
    ''
  )::text as payout_wallet,

  -- Same collapse on the sol side: full sol total under ` + "`" + `waudio_balance` + "`" + `,
  -- ` + "`" + `associated_sol_wallets_balance` + "`" + ` zeroed.
  coalesce(sol_balance, '0') as waudio_balance,
  '0' as associated_sol_wallets_balance,
  blocknumber,
  u.created_at,
  is_storage_v2,
  creator_node_endpoint,

  -- "Of the people I follow, how many also follow this user?"
  --
  -- Compute viewer relationship state once for the whole @ids batch. The
  -- previous correlated shape repeated the mutual-follow count for every
  -- returned user, which multiplied the viewer followee scan by result size.
  -- The CTE above drives from the viewer's followees once and probes the
  -- target batch via the fanout index.
  COALESCE(current_user_followee_follow_counts.count, 0)::bigint AS current_user_followee_follow_count,
  (current_user_following_targets.user_id IS NOT NULL)::bool AS does_current_user_follow,
  (current_user_subscribed_targets.user_id IS NOT NULL)::bool AS does_current_user_subscribe,
  (targets_following_current_user.user_id IS NOT NULL)::bool AS does_follow_current_user,

  handle_lc,
  u.updated_at,
  cover_photo_sizes,
  null as cover_photo_cids, -- todo: what goes in here?
  null as cover_photo_legacy, -- todo:

  profile_picture_sizes,
  null as profile_picture_cids, -- todo
  null as profile_picture_legacy, -- todo

  has_collectibles,
  allow_ai_attribution,
  coin_flair_mint,

  (
    SELECT JSON_BUILD_OBJECT(
      'mint', mint,
      'logo_uri', logo_uri,
      'banner_image_url', banner_image_url,
      'ticker', ticker
    )::jsonb
    FROM artist_coins
    WHERE artist_coins.mint =
      -- User explicitly disabled flair
      CASE WHEN (u.coin_flair_mint = '') THEN NULL
      ELSE COALESCE(
        -- Use preferred flair if valid artist coin and user has a balance
        CASE WHEN (u.coin_flair_mint IS NOT NULL) THEN
          (
            SELECT sol_user_balances.mint
            FROM sol_user_balances
            JOIN artist_coins ON artist_coins.mint = sol_user_balances.mint
            WHERE sol_user_balances.user_id = u.user_id
              AND sol_user_balances.balance > 0
              AND sol_user_balances.mint = u.coin_flair_mint
            LIMIT 1
          )
        ELSE NULL
        END,
        -- Owned first
        (
          SELECT artist_coins.mint
          FROM artist_coins
          WHERE artist_coins.user_id = u.user_id
          LIMIT 1
        ),
        -- Then highest USD value held
        (
          SELECT sol_user_balances.mint
          FROM sol_user_balances
          JOIN artist_coins ON artist_coins.mint = sol_user_balances.mint -- ensure mapped in artist_coins
          LEFT JOIN artist_coin_stats ON artist_coin_stats.mint = sol_user_balances.mint
          LEFT JOIN artist_coin_pools ON artist_coin_pools.base_mint = sol_user_balances.mint
          WHERE sol_user_balances.user_id = u.user_id
            AND sol_user_balances.balance > 0
            AND sol_user_balances.mint NOT IN (
              '9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM', -- ignore prod wAUDIO
              'BELGiMZQ34SDE6x2FUaML2UHDAgBLS64xvhXjX5tBBZo', -- ignore stage wAUDIO
              'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' -- ignore USDC
            )
          ORDER BY (sol_user_balances.balance * COALESCE(artist_coin_stats.price, artist_coin_pools.price_usd, 0)) / POWER(10, artist_coins.decimals) DESC
          LIMIT 1
        )
      )
    END
  ) AS artist_coin_badge

FROM users u
JOIN aggregate_user using (user_id)
LEFT JOIN v_user_balances using (user_id)
LEFT JOIN sol_claimable_accounts spl_user_bank
  ON spl_user_bank.ethereum_address = u.wallet
  AND spl_user_bank.mint = '9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM' -- wAUDIO
LEFT JOIN sol_claimable_accounts usdc_user_bank
  ON usdc_user_bank.ethereum_address = u.wallet
  AND usdc_user_bank.mint = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' -- USDC
LEFT JOIN current_user_followee_follow_counts
  ON current_user_followee_follow_counts.user_id = u.user_id
LEFT JOIN current_user_following_targets
  ON current_user_following_targets.user_id = u.user_id
LEFT JOIN current_user_subscribed_targets
  ON current_user_subscribed_targets.user_id = u.user_id
LEFT JOIN targets_following_current_user
  ON targets_following_current_user.user_id = u.user_id
WHERE u.user_id = ANY($2::int[])
ORDER BY u.user_id
`

type GetUsersParams struct {
	MyID int32   `json:"my_id"`
	Ids  []int32 `json:"ids"`
}

type GetUsersRow struct {
	AlbumCount                     pgtype.Int8     `json:"album_count"`
	ArtistPickTrackID              pgtype.Int4     `json:"artist_pick_track_id"`
	Bio                            pgtype.Text     `json:"bio"`
	CoverPhoto                     pgtype.Text     `json:"cover_photo"`
	FollowerCount                  pgtype.Int8     `json:"follower_count"`
	FolloweeCount                  pgtype.Int8     `json:"followee_count"`
	Handle                         pgtype.Text     `json:"handle"`
	ID                             trashid.HashId  `json:"id"`
	UserID                         int32           `json:"user_id"`
	IsVerified                     bool            `json:"is_verified"`
	TwitterHandle                  pgtype.Text     `json:"twitter_handle"`
	InstagramHandle                pgtype.Text     `json:"instagram_handle"`
	TiktokHandle                   pgtype.Text     `json:"tiktok_handle"`
	VerifiedWithTwitter            pgtype.Bool     `json:"verified_with_twitter"`
	VerifiedWithInstagram          pgtype.Bool     `json:"verified_with_instagram"`
	VerifiedWithTiktok             pgtype.Bool     `json:"verified_with_tiktok"`
	Website                        pgtype.Text     `json:"website"`
	Donation                       pgtype.Text     `json:"donation"`
	Location                       pgtype.Text     `json:"location"`
	Name                           pgtype.Text     `json:"name"`
	PlaylistCount                  pgtype.Int8     `json:"playlist_count"`
	ProfileType                    *string         `json:"profile_type"`
	ProfilePicture                 pgtype.Text     `json:"profile_picture"`
	RepostCount                    pgtype.Int8     `json:"repost_count"`
	TrackCount                     int64           `json:"track_count"`
	IsDeactivated                  bool            `json:"is_deactivated"`
	IsAvailable                    bool            `json:"is_available"`
	ErcWallet                      pgtype.Text     `json:"erc_wallet"`
	SplWallet                      pgtype.Text     `json:"spl_wallet"`
	UsdcWallet                     pgtype.Text     `json:"usdc_wallet"`
	SplUsdcPayoutWallet            pgtype.Text     `json:"spl_usdc_payout_wallet"`
	SupporterCount                 int32           `json:"supporter_count"`
	SupportingCount                int32           `json:"supporting_count"`
	Wallet                         pgtype.Text     `json:"wallet"`
	Balance                        string          `json:"balance"`
	AssociatedWalletsBalance       string          `json:"associated_wallets_balance"`
	TotalBalance                   string          `json:"total_balance"`
	TotalAudioBalance              int32           `json:"total_audio_balance"`
	PayoutWallet                   string          `json:"payout_wallet"`
	WaudioBalance                  string          `json:"waudio_balance"`
	AssociatedSolWalletsBalance    string          `json:"associated_sol_wallets_balance"`
	Blocknumber                    pgtype.Int4     `json:"blocknumber"`
	CreatedAt                      time.Time       `json:"created_at"`
	IsStorageV2                    bool            `json:"is_storage_v2"`
	CreatorNodeEndpoint            pgtype.Text     `json:"creator_node_endpoint"`
	CurrentUserFolloweeFollowCount int64           `json:"current_user_followee_follow_count"`
	DoesCurrentUserFollow          bool            `json:"does_current_user_follow"`
	DoesCurrentUserSubscribe       bool            `json:"does_current_user_subscribe"`
	DoesFollowCurrentUser          bool            `json:"does_follow_current_user"`
	HandleLc                       pgtype.Text     `json:"handle_lc"`
	UpdatedAt                      time.Time       `json:"updated_at"`
	CoverPhotoSizes                pgtype.Text     `json:"cover_photo_sizes"`
	CoverPhotoCids                 interface{}     `json:"cover_photo_cids"`
	CoverPhotoLegacy               interface{}     `json:"cover_photo_legacy"`
	ProfilePictureSizes            pgtype.Text     `json:"profile_picture_sizes"`
	ProfilePictureCids             interface{}     `json:"profile_picture_cids"`
	ProfilePictureLegacy           interface{}     `json:"profile_picture_legacy"`
	HasCollectibles                bool            `json:"has_collectibles"`
	AllowAiAttribution             bool            `json:"allow_ai_attribution"`
	CoinFlairMint                  pgtype.Text     `json:"coin_flair_mint"`
	ArtistCoinBadge                json.RawMessage `json:"artist_coin_badge"`
}

// Each user has at most one Claimable Tokens account per mint in practice;
// this preserves the same join shape (and edge cases) as the legacy
// user_bank_accounts / usdc_user_bank_accounts joins it replaces.
func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.MyID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.AlbumCount,
			&i.ArtistPickTrackID,
			&i.Bio,
			&i.CoverPhoto,
			&i.FollowerCount,
			&i.FolloweeCount,
			&i.Handle,
			&i.ID,
			&i.UserID,
			&i.IsVerified,
			&i.TwitterHandle,
			&i.InstagramHandle,
			&i.TiktokHandle,
			&i.VerifiedWithTwitter,
			&i.VerifiedWithInstagram,
			&i.VerifiedWithTiktok,
			&i.Website,
			&i.Donation,
			&i.Location,
			&i.Name,
			&i.PlaylistCount,
			&i.ProfileType,
			&i.ProfilePicture,
			&i.RepostCount,
			&i.TrackCount,
			&i.IsDeactivated,
			&i.IsAvailable,
			&i.ErcWallet,
			&i.SplWallet,
			&i.UsdcWallet,
			&i.SplUsdcPayoutWallet,
			&i.SupporterCount,
			&i.SupportingCount,
			&i.Wallet,
			&i.Balance,
			&i.AssociatedWalletsBalance,
			&i.TotalBalance,
			&i.TotalAudioBalance,
			&i.PayoutWallet,
			&i.WaudioBalance,
			&i.AssociatedSolWalletsBalance,
			&i.Blocknumber,
			&i.CreatedAt,
			&i.IsStorageV2,
			&i.CreatorNodeEndpoint,
			&i.CurrentUserFolloweeFollowCount,
			&i.DoesCurrentUserFollow,
			&i.DoesCurrentUserSubscribe,
			&i.DoesFollowCurrentUser,
			&i.HandleLc,
			&i.UpdatedAt,
			&i.CoverPhotoSizes,
			&i.CoverPhotoCids,
			&i.CoverPhotoLegacy,
			&i.ProfilePictureSizes,
			&i.ProfilePictureCids,
			&i.ProfilePictureLegacy,
			&i.HasCollectibles,
			&i.AllowAiAttribution,
			&i.CoinFlairMint,
			&i.ArtistCoinBadge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
