// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_audio_transactions.sql

package dbv1

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAudioTransactions = `-- name: GetUserAudioTransactions :many
SELECT ath.created_at as transaction_date, transaction_type, ath.signature, method, ath.user_bank, tx_metadata as metadata, change::text, balance::text
FROM users
JOIN user_bank_accounts uba ON uba.ethereum_address = users.wallet
JOIN audio_transactions_history ath ON ath.user_bank = uba.bank_account
WHERE users.user_id = $1::int AND users.is_current = TRUE
ORDER BY
    CASE WHEN $2::text = 'date' AND $3::text = 'asc' THEN ath.created_at END ASC,
    CASE WHEN $2::text = 'date' AND $3::text = 'desc' THEN ath.created_at END DESC,
    CASE WHEN $2::text = 'type' AND $3::text = 'asc' THEN transaction_type END ASC,
    CASE WHEN $2::text = 'type' AND $3::text = 'desc' THEN transaction_type END DESC
LIMIT $5
OFFSET $4
`

type GetUserAudioTransactionsParams struct {
	UserID        int32  `json:"user_id"`
	SortMethod    string `json:"sort_method"`
	SortDirection string `json:"sort_direction"`
	OffsetVal     int32  `json:"offset_val"`
	LimitVal      int32  `json:"limit_val"`
}

type GetUserAudioTransactionsRow struct {
	TransactionDate time.Time   `json:"transaction_date"`
	TransactionType string      `json:"transaction_type"`
	Signature       string      `json:"signature"`
	Method          string      `json:"method"`
	UserBank        string      `json:"user_bank"`
	Metadata        pgtype.Text `json:"metadata"`
	Change          string      `json:"change"`
	Balance         string      `json:"balance"`
}

func (q *Queries) GetUserAudioTransactions(ctx context.Context, arg GetUserAudioTransactionsParams) ([]GetUserAudioTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getUserAudioTransactions,
		arg.UserID,
		arg.SortMethod,
		arg.SortDirection,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAudioTransactionsRow
	for rows.Next() {
		var i GetUserAudioTransactionsRow
		if err := rows.Scan(
			&i.TransactionDate,
			&i.TransactionType,
			&i.Signature,
			&i.Method,
			&i.UserBank,
			&i.Metadata,
			&i.Change,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAudioTransactionsCount = `-- name: GetUserAudioTransactionsCount :one
SELECT count(*)
FROM users
JOIN user_bank_accounts uba ON uba.ethereum_address = users.wallet
JOIN audio_transactions_history ath ON ath.user_bank = uba.bank_account
WHERE users.user_id = $1::int AND users.is_current = TRUE
`

func (q *Queries) GetUserAudioTransactionsCount(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getUserAudioTransactionsCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
