// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_playlist_ids_by_upc.sql

package dbv1

import (
	"context"
)

const getPlaylistIdsByUPC = `-- name: GetPlaylistIdsByUPC :many
SELECT playlist_id
FROM playlists
WHERE upc = ANY($1::text[])
`

func (q *Queries) GetPlaylistIdsByUPC(ctx context.Context, upcs []string) ([]int32, error) {
	rows, err := q.db.Query(ctx, getPlaylistIdsByUPC, upcs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var playlist_id int32
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
