// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: track_collaborators.sql

package dbv1

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTrackCollaboratorInvitesForUser = `-- name: GetTrackCollaboratorInvitesForUser :many
SELECT track_id, collaborator_user_id, invited_by, status, created_at, updated_at
FROM track_collaborators
WHERE collaborator_user_id = $1::int
  AND ($2::text IS NULL OR status = $2)
ORDER BY created_at DESC
`

type GetTrackCollaboratorInvitesForUserParams struct {
	UserID int32       `json:"user_id"`
	Status pgtype.Text `json:"status"`
}

type GetTrackCollaboratorInvitesForUserRow struct {
	TrackID            int32     `json:"track_id"`
	CollaboratorUserID int32     `json:"collaborator_user_id"`
	InvitedBy          int32     `json:"invited_by"`
	Status             string    `json:"status"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

// A user's collaborator invites/credits, optionally filtered by status
// (pending/accepted/rejected). Backed by the covering
// (collaborator_user_id, status, track_id) index.
func (q *Queries) GetTrackCollaboratorInvitesForUser(ctx context.Context, arg GetTrackCollaboratorInvitesForUserParams) ([]GetTrackCollaboratorInvitesForUserRow, error) {
	rows, err := q.db.Query(ctx, getTrackCollaboratorInvitesForUser, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackCollaboratorInvitesForUserRow
	for rows.Next() {
		var i GetTrackCollaboratorInvitesForUserRow
		if err := rows.Scan(
			&i.TrackID,
			&i.CollaboratorUserID,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackCollaborators = `-- name: GetTrackCollaborators :many
SELECT track_id, collaborator_user_id
FROM track_collaborators
WHERE track_id = ANY($1::int[])
  AND status = 'accepted'
ORDER BY track_id, created_at
`

type GetTrackCollaboratorsRow struct {
	TrackID            int32 `json:"track_id"`
	CollaboratorUserID int32 `json:"collaborator_user_id"`
}

// Accepted collaborators for a set of tracks, used to embed a `collaborators`
// array on track responses. Returns one row per (track, collaborator); the Go
// layer bulk-resolves the user objects. Backed by the track_collaborators
// primary key (track_id leads), so the ANY(...) lookup is index-served.
func (q *Queries) GetTrackCollaborators(ctx context.Context, trackIds []int32) ([]GetTrackCollaboratorsRow, error) {
	rows, err := q.db.Query(ctx, getTrackCollaborators, trackIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackCollaboratorsRow
	for rows.Next() {
		var i GetTrackCollaboratorsRow
		if err := rows.Scan(&i.TrackID, &i.CollaboratorUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
